// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoAcademico.App.Persistencia;

namespace SeguimientoAcademico.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211011141400_Estudiantil4")]
    partial class Estudiantil4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Avance")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Recomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sugerencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamiliarDesignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("FamiliarDesignadoId");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.FamiliarDesignado", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FamiliarDesignado");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Maestro", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("TarjetaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EstudianteId");

                    b.HasDiscriminator().HasValue("Maestro");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Tutor", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("MateriaAsignada")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Actividad", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Actividades")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Materia", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Materias")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Recomendacion", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Recomendaciones")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.FamiliarDesignado", "FamiliarDesignado")
                        .WithMany()
                        .HasForeignKey("FamiliarDesignadoId");

                    b.Navigation("FamiliarDesignado");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Maestro", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Maestros")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Maestros");

                    b.Navigation("Materias");

                    b.Navigation("Recomendaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
