// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoAcademico.App.Persistencia;

namespace SeguimientoAcademico.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211008233658_Estudiantil")]
    partial class Estudiantil
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Avance")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionGeorreferenciada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamiliarDesignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Grado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MateriasInscritas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliarDesignadoId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.FamiliarDesignado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FamiliarDesignados");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Maestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarjetaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Recomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sugerencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Recomendacion");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MateriaAsignada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Actividad", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Actividades")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.FamiliarDesignado", "FamiliarDesignado")
                        .WithMany()
                        .HasForeignKey("FamiliarDesignadoId");

                    b.Navigation("FamiliarDesignado");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Maestro", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Maestros")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Materia", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Materias")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Recomendacion", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Estudiante", null)
                        .WithMany("Recomendaciones")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Maestros");

                    b.Navigation("Materias");

                    b.Navigation("Recomendaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
